title:              YEEmagic's Blog
email:              sehyun5698@gmail.com
description:        Tech blog
author:             YEEmagic
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://yeemagic.github.io/tistory/"

# Social Profiles
twitter_username:   
github_username:    YEEmagic
facebook_username:  
instagram_username:  _3hyun
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
